<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240224103939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE discogs_artist (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, name_variations VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, real_name VARCHAR(255) DEFAULT NULL, profile VARCHAR(255) DEFAULT NULL, releases_url VARCHAR(255) DEFAULT NULL, resource_url VARCHAR(255) DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, images VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE discogs_master (id INT NOT NULL, title VARCHAR(1000) NOT NULL, uri VARCHAR(1000) NOT NULL, year INT NOT NULL, styles JSON DEFAULT NULL, genres JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE discogs_track (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, position INT NOT NULL, duration VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE discogs_video (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, uri VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE user_discogs_master (user_id INT NOT NULL, discogs_master_id INT NOT NULL, PRIMARY KEY(user_id, discogs_master_id))');
        $this->addSql('CREATE INDEX IDX_4FAC6BEFA76ED395 ON user_discogs_master (user_id)');
        $this->addSql('CREATE INDEX IDX_4FAC6BEF6589B466 ON user_discogs_master (discogs_master_id)');
        $this->addSql('ALTER TABLE user_discogs_master ADD CONSTRAINT FK_4FAC6BEFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_discogs_master ADD CONSTRAINT FK_4FAC6BEF6589B466 FOREIGN KEY (discogs_master_id) REFERENCES discogs_master (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE user_discogs_master DROP CONSTRAINT FK_4FAC6BEFA76ED395');
        $this->addSql('ALTER TABLE user_discogs_master DROP CONSTRAINT FK_4FAC6BEF6589B466');
        $this->addSql('DROP TABLE discogs_artist');
        $this->addSql('DROP TABLE discogs_master');
        $this->addSql('DROP TABLE discogs_track');
        $this->addSql('DROP TABLE discogs_video');
        $this->addSql('DROP TABLE user_discogs_master');
    }
}
